- name: Configure Docker host for CloudOps app
  hosts: web
  become: true
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-plugin
          - git
          - curl
        update_cache: true
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

